package com.reactivestax.spring5mvc.repository;

import com.reactivestax.spring5mvc.model.Widget;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.PreparedStatementCreator;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

@Repository
public class WidgetRepositoryImp implements WidgetRepository1{

    @Autowired
    JdbcTemplate jdbcTemplate;

    private KeyHolder generatedKeyHolder = new GeneratedKeyHolder();

    @Override
    public Widget save(Widget widget) {
        String query = "insert into widget_details (Name, Description) values (?,?)";
        Object[] args = new Object[]{widget.getId(), widget.getName(), widget.getDescription()};

        //******** Please see we are using GeneratedKeyHolder to retrieve autogenerated key by mysql
        int i = jdbcTemplate.update(connection -> {
            PreparedStatement ps = connection.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            ps.setString(1, widget.getName());
            ps.setString(2, widget.getDescription());
            return ps;
        }, generatedKeyHolder);
        System.out.println(i);
        int widgetId = generatedKeyHolder.getKey().intValue();
        widget.setId((long) widgetId);
        return widget;
    }
}
